AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31


Parameters:
  ProjectId:
    Type: String
    Description: Books API

Resources:
  ListBooks:
    Type: AWS::Serverless::Function
    Properties:
      Handler: io.openlight.lambda.ListBooksHandler
      Runtime: java8
      Role: arn:aws:iam::963160149973:role/CodeStarWorker-create-user-jav-Lambda
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /books
            Method: get
  GetBook:
      Type: AWS::Serverless::Function
      Properties:
        Handler: io.openlight.lambda.GetBookHandler
        Runtime: java8
        Role: arn:aws:iam::963160149973:role/CodeStarWorker-create-user-jav-Lambda
        Events:
          GetEvent:
            Type: Api
            Properties:
              Path: /books/{bookid}
              Method: get
  CreateBook:
        Type: AWS::Serverless::Function
        Properties:
          Handler: io.openlight.lambda.CreateBookHandler
          Runtime: java8
          Role: arn:aws:iam::963160149973:role/CodeStarWorker-create-user-jav-Lambda
          Events:
            GetEvent:
              Type: Api
              Properties:
                Path: /books
                Method: post
