AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31


Parameters:
  ProjectId:
    Type: String
    Description: Books API
  NeoUser:
      Type: String
      Default: user
      Description: username for neo4j instance
  NeoPassword:
      Type: String
      Default: password
      Description: password for neo4j instance
  NeoUrl:
      Type: String
      Default: localhost
      Description: url for neo4j instance
  BaseUrl:
      Type: String
      Default: localhost
      Description: base url for my APIs

Resources:
  ListBooks:
    Type: AWS::Serverless::Function
    Properties:
      Handler: io.openlight.lambda.ListBooksHandler
      Runtime: java8
      MemorySize: 568
      Timeout: 6
      Environment:
        Variables:
          neo_user: !Ref NeoUser
          neo_password: !Ref NeoPassword
          neo_url: !Ref NeoUrl
          base_url: !Ref BaseUrl
      Role: arn:aws:iam::963160149973:role/CodeStarWorker-create-user-jav-Lambda
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
  GetBook:
      Type: AWS::Serverless::Function
      Properties:
        Handler: io.openlight.lambda.GetBookHandler
        Runtime: java8
        MemorySize: 568
        Timeout: 6
        Environment:
          Variables:
            neo_user: !Ref NeoUser
            neo_password: !Ref NeoPassword
            neo_url: !Ref NeoUrl
            base_url: !Ref BaseUrl
        Role: arn:aws:iam::963160149973:role/CodeStarWorker-create-user-jav-Lambda
        Events:
          GetEvent:
            Type: Api
            Properties:
              Path: /{bookid}
              Method: get
  CreateBook:
        Type: AWS::Serverless::Function
        Properties:
          Handler: io.openlight.lambda.CreateBookHandler
          Runtime: java8
          MemorySize: 568
          Timeout: 6
          Environment:
            Variables:
              neo_user: !Ref NeoUser
              neo_password: !Ref NeoPassword
              neo_url: !Ref NeoUrl
              base_url: !Ref BaseUrl
          Role: arn:aws:iam::963160149973:role/CodeStarWorker-create-user-jav-Lambda
          Events:
            GetEvent:
              Type: Api
              Properties:
                Path: /
                Method: post
  CreateFirstChapter:
        Type: AWS::Serverless::Function
        Properties:
          Handler: io.openlight.lambda.CreateFirstChapterHandler
          Runtime: java8
          MemorySize: 568
          Timeout: 6
          Environment:
            Variables:
              neo_user: !Ref NeoUser
              neo_password: !Ref NeoPassword
              neo_url: !Ref NeoUrl
              base_url: !Ref BaseUrl
          Role: arn:aws:iam::963160149973:role/CodeStarWorker-create-user-jav-Lambda
          Events:
            GetEvent:
              Type: Api
              Properties:
                Path: /{bookid}/chapters
                Method: post
  GetChapter:
          Type: AWS::Serverless::Function
          Properties:
            Handler: io.openlight.lambda.GetChapterHandler
            Runtime: java8
            MemorySize: 568
            Timeout: 6
            Environment:
              Variables:
                neo_user: !Ref NeoUser
                neo_password: !Ref NeoPassword
                neo_url: !Ref NeoUrl
                base_url: !Ref BaseUrl
            Role: arn:aws:iam::963160149973:role/CodeStarWorker-create-user-jav-Lambda
            Events:
              GetEvent:
                Type: Api
                Properties:
                  Path: /{bookid}/chapters/{chapterid}
                  Method: get

  SelectChapter:
          Type: AWS::Serverless::Function
          Properties:
            Handler: io.openlight.lambda.SelectChapterHandler
            Runtime: java8
            MemorySize: 568
            Timeout: 6
            Environment:
              Variables:
                neo_user: !Ref NeoUser
                neo_password: !Ref NeoPassword
                neo_url: !Ref NeoUrl
                base_url: !Ref BaseUrl
            Role: arn:aws:iam::963160149973:role/CodeStarWorker-create-user-jav-Lambda
            Events:
              GetEvent:
                Type: Api
                Properties:
                  Path: /{bookid}/chapters/{chapterid}/select
                  Method: put